# Generated by Django 4.2.27 on 2026-01-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_candidate_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.CharField(default='Interviewer', max_length=100)),
                ('behavior', models.CharField(max_length=20)),
                ('confidence', models.CharField(max_length=20)),
                ('knowledge', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='monitor.interviewsession')),
            ],
        ),
    ]
